name: Update Strings from Google Sheets

on:
  workflow_dispatch:
    inputs:
      spreadsheet_id:
        description: 'The ID of the Google Spreadsheet'
        required: true
        default: ''
      range_name:
        description: 'The Google Sheets Range (e.g., Sheet1!A:F)'
        required: true
        default: ''

jobs:
  update_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client xmltodict

      - name: Run string updater script
        env:
          SPREADSHEET_ID: ${{ github.event.inputs.spreadsheet_id }}
          RANGE_NAME: ${{ github.event.inputs.range_name }}
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          chmod +x ./scripts/strings_updater.sh
          ./scripts/strings_updater.sh
