name: Generate Strings XML

on:
  workflow_dispatch:
    inputs:
      sheet_id:
        description: 'Google Sheet ID'
        required: true
        default: ''
      sheet_range:
        description: 'Google Sheet Range (e.g., Sheet1!A:E)'
        required: true
        default: ''

jobs:
  generate-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google credentials
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Grant execute permission to script
        run: chmod +x ./scripts/strings_updater.sh

      - name: Generate strings.xml
        run: ./scripts/strings_updater.sh ${{ github.event.inputs.sheet_id }} "${{ github.event.inputs.sheet_range }}"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update of strings.xml" || echo "No changes to commit"
          git push
