name: Update Translations

on:
  push:
    branches:
      - main

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client

    - name: Set up Google credentials
      run: |
        echo "${{ secrets.GOOGLE_SHEET_CREDENTIALS }}" > ${{ github.workspace }}/google-credentials.json

    - name: Fetch and generate strings.xml files
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/google-credentials.json
      run: |
        python ${{ github.workspace }}/scripts/fetch_strings.py "${{ secrets.GOOGLE_SHEET_ID }}"

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add app/src/main/res/
        git commit -m "Update translations from Google Sheet" || echo "No changes to commit"
        git push
