name: Fetch Strings from Google Sheets

on:
  workflow_dispatch:
    inputs:
      sheet_id:
        description: 'Enter the Google Sheet ID'
        required: true

jobs:
  fetch_strings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install gspread oauth2client

    - name: Run fetch_strings.py
      env:
        GOOGLE_SHEET_CREDENTIALS: ${{ secrets.CREDENTIALS }}  # Reference the secret here
      run: |
        python /home/runner/work/String-updater/String-updater/scripts/fetch_strings.py ${{ github.event.inputs.sheet_id }}
