name: String Updater

on:
  workflow_dispatch:
    inputs:
      spreadsheet_id:
        description: 'Google Sheets Spreadsheet ID'
        required: true
      range_name:
        description: 'Google Sheets Range (e.g., Sheet1!A:F)'
        required: true
      credentials_json:
        description: 'Base64 Encoded Credentials JSON'
        required: true
      languages:
        description: 'Languages (space-separated, e.g., en de fr)'
        required: true
      language_columns:
        description: 'Column numbers for each language (space-separated, e.g., 3 4 5)'
        required: true

jobs:
  generate-strings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client xmltodict

      - name: Run script to generate strings
        env:
          SPREADSHEET_ID: ${{ github.event.inputs.spreadsheet_id }}
          RANGE_NAME: ${{ github.event.inputs.range_name }}
          CREDENTIALS_JSON: ${{ github.event.inputs.credentials_json }}
          LANGUAGES: ${{ github.event.inputs.languages }}
          LANGUAGE_COLUMNS: ${{ github.event.inputs.language_columns }}
        run: |
          chmod +x ./scripts/string_updater.sh
          ./scripts/string_updater.sh
