name: String Updater

on:
  workflow_dispatch:
    inputs:
      spreadsheet_id:
        description: 'Google Sheets ID'
        required: true
      range_name:
        description: 'Google Sheets Range (e.g., Sheet1!A:F)'
        required: true
      credentials_json:
        description: 'Credentials JSON (raw JSON)'
        required: true

jobs:
  update_strings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client xmltodict

      - name: Run string updater script
        env:
          SPREADSHEET_ID: ${{ github.event.inputs.spreadsheet_id }}
          RANGE_NAME: ${{ github.event.inputs.range_name }}
          CREDENTIALS_JSON: ${{ github.event.inputs.credentials_json }}
        run: |
          chmod +x ./scripts/strings_updater.sh
          ./scripts/strings_updater.sh
