name: String Updater

on:
  workflow_dispatch:
    inputs:
      spreadsheet_id:
        description: 'Google Sheets ID'
        required: true
        default: ''
      credentials_json:
        description: 'Base64 encoded credentials JSON'
        required: true
        default: ''
      range_name:
        description: 'Google Sheets Range (e.g., Sheet1!A:F)'
        required: true
        default: 'Sheet1!A:F'

jobs:
  update_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip install gspread oauth2client xmltodict

      - name: Decode Credentials
        run: |
          echo ${{ github.event.inputs.credentials_json }} | base64 --decode > credentials.json

      - name: Run String Updater Script
        run: |
          chmod +x ./scripts/string_updater.sh
          ./scripts/string_updater.sh
        env:
          CREDENTIALS_JSON: ${{ github.event.inputs.credentials_json }}
          SHEET_ID: ${{ github.event.inputs.spreadsheet_id }}
          RANGE_NAME: ${{ github.event.inputs.range_name }}
