name: Update Android Strings

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  update-strings:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client xmltodict
      
      - name: Run strings updater script
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          chmod +x scripts/strings_updater.sh
          bash scripts/strings_updater.sh
      
      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add android/res/
          git commit -m "Update Android strings"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
