name: Fetch Strings from Google Sheets

on:
  workflow_dispatch:
    inputs:
      sheet_id:
        description: 'Enter the Google Sheet ID'
        required: true
      gid:
        description: 'Enter the GID for the worksheet (leave empty for default GID 0)'
        required: false

jobs:
  fetch_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client jq

      - name: Make fetch_strings.sh executable
        run: chmod +x scripts/fetch_strings.sh

      - name: Run fetch_strings.sh
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}  # Set environment variable here
        run: |
          ./scripts/fetch_strings.sh ${{ github.event.inputs.sheet_id }} "${{ github.event.inputs.gid }}"

      - name: Configure Git
        run: |
          git config --local user.name "${{ secrets.USER_NAME }}"
          git config --local user.email "${{ secrets.USER_EMAIL }}"

      - name: Commit and push changes
        run: |
          git add resources/
          git commit -m "Add generated strings.xml and Localizable.strings files from Google Sheets"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
