name: Fetch Strings from Google Sheets

on:
  workflow_dispatch:
    inputs:
      sheet_id:
        description: 'Enter the Google Sheet ID'
        required: true

jobs:
  fetch_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client jq

      - name: Create fetch_strings.sh script
        run: |
          cat << 'EOF' > fetch_strings.sh
          #!/bin/bash

          # Fetch strings from Google Sheets and generate strings.xml files

          # Check for required environment variable
          if [ -z "$CREDENTIALS" ]; then
              echo "Error: CREDENTIALS is not set."
              exit 1
          fi

          # Check for required argument
          if [ "$#" -ne 1 ]; then
              echo "Usage: $0 <sheet_id>"
              exit 1
          fi

          SHEET_ID=$1
          VALUES_DIR="./resources"

          # Create output directory if it does not exist
          mkdir -p "$VALUES_DIR"

          # Fetch data from Google Sheets using Python
          DATA=$(python - <<END
          import os
          import json
          import gspread
          from oauth2client.service_account import ServiceAccountCredentials

          # Use credentials and authenticate
          scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']

          # Load the credentials from the environment variable
          creds_json = os.getenv('CREDENTIALS')
          creds_data = json.loads(creds_json)
          creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_data, scope)

          client = gspread.authorize(creds)

          # Open the spreadsheet by ID and fetch the first worksheet
          sheet = client.open_by_key("$SHEET_ID")
          worksheet = sheet.get_worksheet(0)  # Get the first worksheet

          # Fetch all records from the worksheet
          data = worksheet.get_all_records()
          print(json.dumps(data))
          END
          )

          # Check for JSON parsing errors
          if [ $? -ne 0 ]; then
              echo "Error fetching data from Google Sheets."
              exit 1
          fi

          # Prepare associative arrays to hold translations
          declare -A translations

          # Process each row and collect translations
          echo "$DATA" | jq -c '.[]' | while IFS= read -r row; do
              id=$(echo "$row" | jq -r '.ID')
              type=$(echo "$row" | jq -r '.Type')

              # Handle string and plural types
              if [ "$type" == "string" ]; then
                  lang=$(echo "$row" | jq -r 'keys_unsorted[] | select(. != "ID" and . != "Type" and . != "Quantity")')
                  for lang_code in $lang; do
                      translation=$(echo "$row" | jq -r ".\"$lang_code\"")
                      translations["$lang_code,$id"]="$translation"
                  done
              elif [ "$type" == "plural" ]; then
                  for lang_code in $(echo "$row" | jq -r 'keys_unsorted[] | select(. != "ID" and . != "Type" and . != "Quantity")'); do
                      singular=$(echo "$row" | jq -r ".\"$lang_code\" | select(. != null) | .singular")
                      plural=$(echo "$row" | jq -r ".\"$lang_code\" | select(. != null) | .plural")
                      translations["$lang_code,$id,one"]="$singular"
                      translations["$lang_code,$id,other"]="$plural"
                  done
              fi
          done

          # Generate strings.xml for each language
          for lang in "${!translations[@]}"; do
              lang_code="${lang%%,*}"
              id="${lang##*,}"

              lang_dir="$VALUES_DIR/values-${lang_code}"
              mkdir -p "$lang_dir"
              xml_file="$lang_dir/strings.xml"

              # Start writing the XML if file does not exist
              if [ ! -f "$xml_file" ]; then
                  {
                      echo '<?xml version="1.0" encoding="utf-8"?>'
                      echo '<resources>'
                  } > "$xml_file"
              fi

              # Append the translation string
              translation=${translations["$lang"]}
              if [[ "$id" == *","* ]]; then
                  # This is a plural string
                  echo "    <plurals name=\"$id\">" >> "$xml_file"
                  echo "        <item quantity=\"one\">${translations["$lang_code,$id,one"]}</item>" >> "$xml_file"
                  echo "        <item quantity=\"other\">${translations["$lang_code,$id,other"]}</item>" >> "$xml_file"
                  echo "    </plurals>" >> "$xml_file"
              else
                  echo "    <string name=\"$id\">$translation</string>" >> "$xml_file"
              fi
          done

          # Close the resources tag for each language file
          for lang in $(ls $VALUES_DIR | grep 'values-'); do
              xml_file="$VALUES_DIR/$lang/strings.xml"
              echo '</resources>' >> "$xml_file"
              echo "strings.xml updated for $lang"
          done
          EOF

      - name: Make fetch_strings.sh executable
        run: chmod +x fetch_strings.sh

      - name: Run fetch_strings.sh
        env: 
          CREDENTIALS: ${{ secrets.CREDENTIALS }}  # Set environment variable here
        run: |
          ./fetch_strings.sh ${{ github.event.inputs.sheet_id }}

      - name: Configure Git
        run: |
          git config --local user.name "${{ secrets.USER_NAME }}"
          git config --local user.email "${{ secrets.USER_EMAIL }}"

      - name: Commit and push changes
        run: |
          git add resources/
          git commit -m "Add generated strings.xml files from Google Sheets"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
