name: Fetch Strings from Google Sheets

on:
  workflow_dispatch:
    inputs:
      sheet_id:
        description: 'Enter the Google Sheet ID'
        required: true

jobs:
  fetch_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client jq

      - name: Make fetch_strings.sh executable
        run: chmod +x fetch_strings.sh

      - name: Run fetch_strings.sh
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}  # Get CREDENTIALS from GitHub Secrets
        run: ./scripts/fetch_strings.sh ${{ github.event.inputs.sheet_id }}
