name: String Updater

on:
  push:
    branches:
      - main  # Adjust this to your target branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client xmltodict --quiet

      - name: Run string updater script
        run: |
          chmod +x ./scripts/strings_updater.sh
          ./scripts/strings_updater.sh

      - name: Ensure generated_strings directory exists
        run: |
          mkdir -p generated_strings  # Create the directory if it doesn't exist

      - name: Commit and push generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add generated_strings || echo "No new files to add"
          git commit -m "Update generated strings" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
